#### Preamble ####
# Purpose: Generates a simulated version of the Toronto Shelter
# Author: Xizi Sun
# Date: 23 September 2024
# Contact: xizi.sun@mail.utoronto.ca
# License: MIT
# Pre-requisites: Install the tidyverse
# Any other information needed? no

# Load necessary libraries
library(dplyr)

# Define the population groups
population_groups <- c("All Population", "Chronic", "Refugees", "Families", "Youth", "Single Adult", "Non-refugees")

# Set up the simulation for 12 months (2018), monthly data with the new date format 'date.mmm.yy'
set.seed(123)
n_months <- 12 # Simulate for 12 months
dates <- format(seq(as.Date("2018-01-01"), by = "month", length.out = n_months), "%b-%y")

# Create simulated data
# Generated by ChatGPT
simulated_data <- data.frame(
  date.mmm.yy = rep(dates, each = length(population_groups)),
  population_group = rep(population_groups, times = n_months),
  returned_to_shelter = sample(0:1200, n_months * length(population_groups), replace = TRUE),
  returned_from_housing = sample(0:600, n_months * length(population_groups), replace = TRUE),
  ageunder16 = sample(0:1500, n_months * length(population_groups), replace = TRUE),
  age16.24 = sample(0:1500, n_months * length(population_groups), replace = TRUE),
  age25.34 = sample(0:1500, n_months * length(population_groups), replace = TRUE),
  age35.44 = sample(0:1500, n_months * length(population_groups), replace = TRUE),
  age45.54 = sample(0:1500, n_months * length(population_groups), replace = TRUE),
  age55.64 = sample(0:1500, n_months * length(population_groups), replace = TRUE),
  age65over = sample(0:1500, n_months * length(population_groups), replace = TRUE)
)

# Preview the simulated data
head(simulated_data)

#  save to a CSV
write_csv(simulated_data, here::here("data", "raw_data", "simulated_data.csv"))

# View the first few rows of the simulated data
head(simulated_data)
